name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool libffi-dev \
            pkg-config zip unzip openjdk-11-jdk git python3-pip ccache

      - name: Add user base binary to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install pip & Buildozer
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install --user buildozer cython

      - name: Set up Android SDK & NDK
        run: |
          mkdir -p android && cd android
          
          # Download and extract Android SDK
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip -d cmdline-tools
          mkdir -p android-sdk/cmdline-tools/latest
          mv cmdline-tools/* android-sdk/cmdline-tools/latest
          
          # Download and extract Android NDK
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          
          echo "ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android/android-ndk-r25b" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/android/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Accept SDK Licenses and Install Packages
        run: |
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" "platforms;android-31" "build-tools;33.0.2" "ndk;25.1.8937393"

      - name: Prepare buildozer.spec if needed
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi
          sed -i 's|^#*android.accept_sdk_license *=.*|android.accept_sdk_license = True|' buildozer.spec
          sed -i 's|^#*android.sdk_path *=.*|android.sdk_path = ./android/android-sdk|' buildozer.spec
          sed -i 's|^#*android.ndk_path *=.*|android.ndk_path = ./android/android-ndk-r25b|' buildozer.spec

      - name: Build APK
        run: ~/.local/bin/buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
