name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          openjdk-11-jdk \
          zlib1g-dev \
          libncurses5-dev \
          libgdbm-dev \
          libnss3-dev \
          libssl-dev \
          libsqlite3-dev \
          libreadline-dev \
          libffi-dev \
          libbz2-dev \
          cmake \
          ninja-build \
          pkg-config \
          liblzma-dev

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip virtualenv
        python3 -m pip install cython==0.29.33

    - name: Set up Python-for-Android
      run: |
        python3 -m pip install buildozer
        buildozer init
        # Modify buildozer.spec as needed (you might want to commit your own version)
        sed -i 's/#android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        sed -i 's/#android.ndk_path = .*/android.ndk_path = .\/android\/android-ndk-r25b/' buildozer.spec
        sed -i 's/#android.sdk_path = .*/android.sdk_path = .\/android\/android-sdk/' buildozer.spec

    - name: Download Android SDK and NDK
      run: |
        mkdir -p android
        cd android
        # Download Android NDK
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip
        mv android-ndk-r25b android-ndk-r25b
        rm android-ndk-r25b-linux.zip
        
        # Download Android SDK
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir android-sdk
        mv cmdline-tools android-sdk/cmdline-tools
        rm commandlinetools-linux-9477386_latest.zip
        
        # Set environment variables
        echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r25b" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$(pwd)/android-sdk" >> $GITHUB_ENV
        echo "PATH=$(pwd)/android-sdk/cmdline-tools/bin:$(pwd)/android-ndk-r25b:$PATH" >> $GITHUB_ENV

    - name: Accept Android licenses
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --licenses

    - name: Install Android platform tools
      run: |
        $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug
        ls -la bin/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: kivy-app
        path: bin/*.apk
